name: pull_request_target

on:
  pull_request_target:
    branches: main
    types:
      - closed
permissions:
  contents: read
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "BASE_SHA: $BASE_SHA"
          echo "MERGE_COMMIT_SHA: $MERGE_COMMIT_SHA"
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          MERGE_COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}

      - run: cat README.md
